// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/payments.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	mi := &file_api_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_api_payments_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ChargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ChargeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeReply) Reset() {
	*x = ChargeReply{}
	mi := &file_api_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeReply) ProtoMessage() {}

func (x *ChargeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeReply.ProtoReflect.Descriptor instead.
func (*ChargeReply) Descriptor() ([]byte, []int) {
	return file_api_payments_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_payments_proto_rawDescGZIP(), []int{2}
}

func (x *RefundRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RefundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundReply) Reset() {
	*x = RefundReply{}
	mi := &file_api_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundReply) ProtoMessage() {}

func (x *RefundReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundReply.ProtoReflect.Descriptor instead.
func (*RefundReply) Descriptor() ([]byte, []int) {
	return file_api_payments_proto_rawDescGZIP(), []int{3}
}

func (x *RefundReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_payments_proto protoreflect.FileDescriptor

const file_api_payments_proto_rawDesc = "" +
	"\n" +
	"\x12api/payments.proto\x12\vpayments.v1\"B\n" +
	"\rChargeRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"%\n" +
	"\vChargeReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"F\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"%\n" +
	"\vRefundReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x8a\x01\n" +
	"\bPayments\x12>\n" +
	"\x06Charge\x12\x1a.payments.v1.ChargeRequest\x1a\x18.payments.v1.ChargeReply\x12>\n" +
	"\x06Refund\x12\x1a.payments.v1.RefundRequest\x1a\x18.payments.v1.RefundReplyB\x1dZ\x1bauthz-system/api;paymentsv1b\x06proto3"

var (
	file_api_payments_proto_rawDescOnce sync.Once
	file_api_payments_proto_rawDescData []byte
)

func file_api_payments_proto_rawDescGZIP() []byte {
	file_api_payments_proto_rawDescOnce.Do(func() {
		file_api_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payments_proto_rawDesc), len(file_api_payments_proto_rawDesc)))
	})
	return file_api_payments_proto_rawDescData
}

var file_api_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_payments_proto_goTypes = []any{
	(*ChargeRequest)(nil), // 0: payments.v1.ChargeRequest
	(*ChargeReply)(nil),   // 1: payments.v1.ChargeReply
	(*RefundRequest)(nil), // 2: payments.v1.RefundRequest
	(*RefundReply)(nil),   // 3: payments.v1.RefundReply
}
var file_api_payments_proto_depIdxs = []int32{
	0, // 0: payments.v1.Payments.Charge:input_type -> payments.v1.ChargeRequest
	2, // 1: payments.v1.Payments.Refund:input_type -> payments.v1.RefundRequest
	1, // 2: payments.v1.Payments.Charge:output_type -> payments.v1.ChargeReply
	3, // 3: payments.v1.Payments.Refund:output_type -> payments.v1.RefundReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_payments_proto_init() }
func file_api_payments_proto_init() {
	if File_api_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payments_proto_rawDesc), len(file_api_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payments_proto_goTypes,
		DependencyIndexes: file_api_payments_proto_depIdxs,
		MessageInfos:      file_api_payments_proto_msgTypes,
	}.Build()
	File_api_payments_proto = out.File
	file_api_payments_proto_goTypes = nil
	file_api_payments_proto_depIdxs = nil
}
